name: Code Quality

on:
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npx tsc --noEmit

      - name: Lint code
        run: npm run lint

      - name: Build project
        env:
          NEXT_PUBLIC_SITE_URL: https://deviscript.github.io
          NEXT_PUBLIC_SITE_NAME: Brian Lockhart Portfolio
        run: npm run build
