# GitHub Pages deployment disabled - now using Vercel for deployment
# This workflow has been commented out since Vercel handles automatic deployment
# from the main branch. If you need to re-enable GitHub Pages deployment,
# uncomment the configuration below.

# name: Deploy to GitHub Pages
#
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
#
# permissions:
#   contents: read
#   pages: write
#   id-token: write
#
# concurrency:
#   group: "pages"
#   cancel-in-progress: false
#
# jobs:
#   deploy:
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#
#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '18'
#           cache: 'npm'
#
#       - name: Install dependencies
#         run: npm ci
#
#       - name: Build
#         run: npm run build
#
#       - name: Deploy to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./out
